spring.application.name=digit
spring.datasource.url=jdbc:postgresql://localhost:5432/pawpaw
spring.datasource.username=postgres
spring.datasource.password=nova123
spring.jpa.hibernate.ddl-auto=update
server.port=8081
